version: '3.3'

services:
   rabbit.bizagi:
     image: bizagiresearch/rabbitmq-autocluster
     network_mode: bridge
     environment:
       RABBITMQ_ERLANG_COOKIE: LHSCFNZRICYCDVYLIUUC
       ETCD_HOST: 172.17.0.3
       ETCD_PORT: 2379
       AUTOCLUSTER_TYPE: etcd
       AUTOCLUSTER_LOG_LEVEL: debug
       RABBITMQ_USE_LONGNAME: "true"
     ports:
         - "15673:15672"
         